name: Terraform Plan POC

on:
  workflow_dispatch:
  push:
    branches:
      - prod

permissions:
  contents: read

concurrency:
  group: terraform-state-poc
  cancel-in-progress: false

jobs:
  plan:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      working-directory: environment/POC
      terraform-version: "1.5.7"
      environment-name: POC