name: Terraform CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - prod

permissions:
  contents: read
  id-token: write

concurrency:
  group: terraform-ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate:
    name: Terraform validate
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      
      - uses: ./.github/actions/terraform-validate.yml
        with:
          working-directory: environment/POC
          terraform-version: "1.5.7"

  security:
    name: Terraform security
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      
      - uses: ./.github/actions/terraform-security.yml
        with:
          scan-directory: .